//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Multiverse_Runtime_LuaScriptWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Multiverse.Runtime.LuaScript), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Load", Load);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("luaScript", get_luaScript, set_luaScript);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Multiverse.Runtime.LuaScript obj = (Multiverse.Runtime.LuaScript)ToLua.CheckObject<Multiverse.Runtime.LuaScript>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Load(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_luaScript(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Multiverse.Runtime.LuaScript obj = (Multiverse.Runtime.LuaScript)o;
			string ret = obj.luaScript;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index luaScript on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_luaScript(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Multiverse.Runtime.LuaScript obj = (Multiverse.Runtime.LuaScript)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.luaScript = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index luaScript on a nil value");
		}
	}
}

